apps/blog/urls.py
from django.conf.urls import patterns, url
#import views
#
#urlpatterns = patterns(views,
#    # Examples:
#    # url(r'^$', 'django_blog.views.home', name='home'),
#    url(r'^hello/', views.hello),
#    url(r'^index$', views.index),
#    url(r'^$', views.index),
#    url(r'^(?P<blog_id>\d+)/(?P<blog_link>\w*)$', views.blog_detail),
#)

urlpatterns = patterns('apps.blog.views',

    #url(r'^index$', 'index', name='index'),
    url(r'^$', 'blog_home'),
    url(r'^(?P<blog_id>\d+)/(?P<blog_link>[\w,-]*)$', 'blog_detail', name='blog_detail'),
    url(r'^author/(?P<username>\w+)$', 'author_blogs', name='author_blogs'),
    url(r'^archives$', 'archives', name='archives'),
    url(r'^tag/(?P<tag_title>[\w,-]*)$','tag', name='tag'),
    url(r'^search/$','SearchViews',name='SearchViews'),
)

django_blog/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from django_blog.sitemaps import BlogSitemap
from django_blog.sitemaps import StaticViewSitemap

admin.autodiscover()

sitemaps = {
    'blog': BlogSitemap,
    'static': StaticViewSitemap
}

from django_blog import settings
urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'apps.blog.views.index', name='home'),
    url(r'^about$','apps.blog.views.about', name='about'),
    url(r'^blog/', include('apps.blog.urls', namespace='blog')),
    #url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    #url(r'^grappelli/',include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'404', 'apps.blog.views.not_found'),
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap',{'sitemaps':sitemaps}),
    #gallery
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root':settings.MEDIA_ROOT}),
    url(r'^items/', include('apps.items.urls')),
    #djangoueditor
    #url(r'^ueditor/',include('DjangoUeditor.urls' )),
    #url(r'^cms/', include('apps.cms.urls', namespace='cms')),
    url(r'^ckeditor/', include('ckeditor.urls')),
)

templates/base.html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{% block description %}{% endblock %}">

     
    <meta name="author" content="atyu30">
    <title>{% block title %}{% endblock %}</title>
    {% load staticfiles %}
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "css/blog-home.css" %}" rel="stylesheet">
    <link href="{% static "css/github.css" %}" rel="stylesheet">
    {% comment %}
    {% load compress %}
    {% compress css %}
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "css/blog-home.css" %}" rel="stylesheet">
    <link href="{% static "css/github.css" %}" rel="stylesheet">
    {% endcompress %}
    {% endcomment %}


</head>
<body>

    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                    <a class="navbar-brand" href="/">YUYIZHI</a>
                    <a class="navbar-brand" href="/items/">相册</a>
                    <a class="navbar-brand" href="/admin/">管理</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'blog:archives' %}">Archives</a>
                    </li>
                    <li><a href="{% url 'about' %}">About</a>
                    </li>
                </ul>
                {{uid}}
                {% if request.user.is_superuser %}
                <div class="navbar-user">
                    <a class="navbar-brand" href="/admin">{{request.user}}</a>
                </div>
                {%endif%}
            </div>
            <!-- /.navbar-collapse -->
            
        </div>
        <!-- /.container -->
    </nav>

    <div class="container">

        <div class="row">
            <div id="floater"></div>
            <div class="col-lg-8">{% block content %} {% endblock %}</div>
            {% block panel %} {%endblock %}
        </div>
        <hr>
        <footer>
            <div class="row footer">
                <div class="col-lg-12">
                    <p>Copyright &copy; Atyu30 2014 
                    <span>管理:
                        <a href="/admin/">Admin</a>
                    </span>
                    </p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->
    {% comment %}
    {% compress js %}
    <script src="{% static "js/jquery-1.10.2.js" %}"></script>
    <script src="{% static "js/bootstrap.js" %}"></script>
    <script src="{% static "js/blog.js" %}"></script>
    {% endcompress %}
    {%endcomment%}

    <script src="{% static "js/jquery.min.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static "js/blog.js" %}"></script>
    <script src="{% static "js/tagcloud.js" %}"></script>
    <script>
        $.fn.tagcloud.defaults = {
          size: {start: 10, end: 18, unit: 'pt'},
        };
        
        $(function () {
          $('#whatever a').tagcloud();
        });
    </script>
</body>

</html>