apps/blog/urls.py
from django.conf.urls import patterns, url
#import views
#
#urlpatterns = patterns(views,
#    # Examples:
#    # url(r'^$', 'django_blog.views.home', name='home'),
#    url(r'^hello/', views.hello),
#    url(r'^index$', views.index),
#    url(r'^$', views.index),
#    url(r'^(?P<blog_id>\d+)/(?P<blog_link>\w*)$', views.blog_detail),
#)

urlpatterns = patterns('apps.blog.views',

    #url(r'^index$', 'index', name='index'),
    url(r'^$', 'blog_home'),
    url(r'^(?P<blog_id>\d+)/(?P<blog_link>[\w,-]*)$', 'blog_detail', name='blog_detail'),
    url(r'^author/(?P<username>\w+)$', 'author_blogs', name='author_blogs'),
    url(r'^archives$', 'archives', name='archives'),
    url(r'^tag/(?P<tag_title>[\w,-]*)$','tag', name='tag'),
    url(r'^search/$','SearchViews',name='SearchViews'),
)

django_blog/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from django_blog.sitemaps import BlogSitemap
from django_blog.sitemaps import StaticViewSitemap

admin.autodiscover()

sitemaps = {
    'blog': BlogSitemap,
    'static': StaticViewSitemap
}

from django_blog import settings
urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'apps.blog.views.index', name='home'),
    url(r'^about$','apps.blog.views.about', name='about'),
    url(r'^blog/', include('apps.blog.urls', namespace='blog')),
    #url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    #url(r'^grappelli/',include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'404', 'apps.blog.views.not_found'),
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap',{'sitemaps':sitemaps}),
    #gallery
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root':settings.MEDIA_ROOT}),
    url(r'^items/', include('apps.items.urls')),
    #djangoueditor
    #url(r'^ueditor/',include('DjangoUeditor.urls' )),
    #url(r'^cms/', include('apps.cms.urls', namespace='cms')),
    url(r'^ckeditor/', include('ckeditor.urls')),
)

templates/widget/blog-info.html
 <p class="article-info article-preview">
    
    <span class="glyphicon glyphicon-time"></span><span class="info">{{blog.add_time|date:"Y-m-d"}}</span>

    {% if not blog.is_public %}
        <span class="glyphicon glyphicon-lock"></span>
    {% else %}
        <span class="glyphicon glyphicon-user"></span>
    {%endif %}
    <span class="info"><a href="{% url 'blog:author_blogs' blog.author.username %}">{{blog.author.username}}</a></span>

    {% if blog.tags.all %}
        <span class="glyphicon glyphicon-tags"> </span>
        {% for tag in blog.tags.all %}
            <a href="{% url 'blog:tag' tag.title %}" class="tag info">
                <span class="label label-default">{{tag.title}}</span> 
            </a>
        {% endfor %}
    {%endif%}
</p>

templates/widget/panel.html
<div class="col-lg-4">
    <div class="well">
        <div class="input-group">
            <form action="/blog/search/" method="get" align="right">
            <input type="text" name="search" class="form-control" id="blog-query" />
            <span class="glyphicon glyphicon-search">
            <input type="submit" value="Search" />
            </span>

            </form>
        </div>
    </div>
    <!-- Tag -->
    <div class="well" id="whatever">
        <h4>Tags</h4>
                    {% for title, count in tags %}
                    <a href="{% url 'blog:tag' title %}" rel="{{count}}">{{title}}</a>
                    {% endfor %}
    </div>

    <!-- github -->
    <div class="well">
        <h4>GitHub</h4>
        <p><a href="https://github.com/atyu30">A blog based on django and bootstrap3</a></p>
    </div>

</div>